name: Terraform Validate

# Runs the terraform fmt check on pull requests that touch Terraform files.
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.tf"
      - "**.tf.json"
      - "**.tftest.hcl"

jobs:
  validate:
    uses: ./.github/workflows/terraform-validate.yml
