name: Terraform Format

# Runs the terraform fmt check on pull requests that touch Terraform files.
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.tf"
      - "**.tf.json"
      - "**.tftest.hcl"

jobs:
  fmt:
    uses: ./.github/workflows/terraform-fmt.yml
